name: Build and Deploy Streamlit App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build and Deploy Streamlit App
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js for frontend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # Create frontend files
      - name: Create frontend structure and files
        run: |
          mkdir -p wallet/frontend/public wallet/frontend/src
          echo '{
            "name": "frontend",
            "version": "1.0.0",
            "dependencies": {
              "react": "^18.2.0",
              "react-dom": "^18.2.0",
              "web3": "^1.10.0",
              "@ethersproject/providers": "^5.7.2",
              "streamlit-component-lib": "^1.3.0",
              "react-scripts": "^5.0.1"
            },
            "scripts": {
              "start": "react-scripts start",
              "build": "react-scripts build"
            }
          }' > wallet/frontend/package.json
          echo "<!DOCTYPE html><html><head><title>Wallet Component</title></head><body><div id='root'></div></body></html>" > wallet/frontend/public/index.html
          echo "import React from 'react';" > wallet/frontend/src/WalletConnect.js
          echo "import { Web3Provider } from '@ethersproject/providers';" >> wallet/frontend/src/WalletConnect.js
          echo "export default function WalletConnect() { return <button>Connect Wallet</button>; }" >> wallet/frontend/src/WalletConnect.js
          echo "import React from 'react'; import ReactDOM from 'react-dom'; import WalletConnect from './WalletConnect'; ReactDOM.render(<WalletConnect />, document.getElementById('root'));" > wallet/frontend/src/index.js

      # Install frontend dependencies
      - name: Install frontend dependencies
        working-directory: wallet/frontend
        run: |
          npm install

      # Build frontend
      - name: Build frontend
        working-directory: wallet/frontend
        run: |
          npm run build

      # Create Streamlit app
      - name: Create Streamlit app
        run: |
          mkdir -p wallet
          echo "import streamlit as st" > wallet/app.py
          echo "from streamlit.components.v1 import declare_component" >> wallet/app.py
          echo "wallet_component = declare_component('wallet_component', path='./frontend/build')" >> wallet/app.py
          echo "st.title('Wallet Connect Test')" >> wallet/app.py
          echo "wallet_address = wallet_component()" >> wallet/app.py
          echo "if wallet_address:" >> wallet/app.py
          echo "    st.success(f'Wallet Connected: {wallet_address}')" >> wallet/app.py
          echo "else:" >> wallet/app.py
          echo "    st.warning('Please connect your wallet.')" >> wallet/app.py

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install streamlit

      # Deploy Streamlit app
      - name: Deploy Streamlit app
        env:
          STREAMLIT_SERVER_PORT: 8501
        run: |
          echo "Deploying Streamlit app..."
          streamlit run wallet/app.py --server.headless true
