name: Build and Deploy Streamlit Component

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    name: Build and Test Streamlit Component
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js for frontend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # Create frontend directory and files
      - name: Create frontend files
        run: |
          mkdir -p wallet_component/frontend/public wallet_component/frontend/src
          echo '{
            "name": "frontend",
            "version": "1.0.0",
            "dependencies": {
              "react": "^18.2.0",
              "react-dom": "^18.2.0",
              "web3": "^1.10.0",
              "streamlit-component-lib": "^1.3.0",
              "react-scripts": "^5.0.1"
            },
            "scripts": {
              "start": "react-scripts start",
              "build": "react-scripts build"
            }
          }' > wallet_component/frontend/package.json
          echo "<!DOCTYPE html><html><head><title>Wallet Component</title></head><body><div id='root'></div></body></html>" > wallet_component/frontend/public/index.html
          echo "import React from 'react';" > wallet_component/frontend/src/WalletConnect.js
          echo "import { Web3Provider } from '@ethersproject/providers';" >> wallet_component/frontend/src/WalletConnect.js
          echo "export default function WalletConnect() { return <button>Connect Wallet</button>; }" >> wallet_component/frontend/src/WalletConnect.js
          echo "import React from 'react'; import ReactDOM from 'react-dom'; import WalletConnect from './WalletConnect'; ReactDOM.render(<WalletConnect />, document.getElementById('root'));" > wallet_component/frontend/src/index.js

      # Install frontend dependencies
      - name: Install frontend dependencies
        working-directory: wallet_component/frontend
        run: |
          npm install

      # Build frontend
      - name: Build frontend
        working-directory: wallet_component/frontend
        run: |
          npm run build

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install streamlit

      # Test Streamlit app locally
      - name: Test Streamlit app locally
        env:
          STREAMLIT_SERVER_PORT: 8501
        run: |
          source venv/bin/activate
          streamlit run wallet_component/app.py --server.headless true
