name: Build and Deploy Wallet App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_deploy:
    name: Build and Deploy Wallet App
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Node.js for Frontend
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    # Step 3: Install Frontend Dependencies and Build
    - name: Install and Build Frontend
      run: |
        echo "Installing and building frontend..."
        cd wallet/frontend
        npm install
        npm run build

    # Step 4: Commit and Push Changes to Repository
    - name: Commit and Push Built Frontend Files
      run: |
        echo "Committing and pushing changes..."
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add wallet/frontend/build
        git commit -m "Automated build: Add generated frontend assets"
        git push origin main || echo "No changes to push"

    # Step 5: Set up Python for Backend
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Step 6: Install Python Dependencies
    - name: Install Backend Dependencies
      run: |
        echo "Installing backend dependencies..."
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r wallet/requirements.txt

    # Step 7: Deploy Streamlit App (optional)
    - name: Deploy Streamlit App (Optional)
      if: ${{ always() }}
      run: |
        echo "Streamlit app deployment step. Comment this out if running manually."
        source venv/bin/activate
        streamlit run wallet/app.py --server.headless true || echo "Skipping deployment for manual setup."
